---
# tasks file for zabbix_agent

- name: Скачивание zabbix-release
  ansible.builtin.get_url:
    url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu22.04_all.deb"
    dest: /tmp/zabbix-release.deb

- name: Установка zabbix-release
  apt:
    deb: /tmp/zabbix-release.deb

- name: Обновление apt
  apt:
    update_cache: yes

- name: Установка zabbix_agent
  apt:
    name: "zabbix-agent"
    state: present

# настройка конфига
- name: Добавить блок строк в конец файла
  blockinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    block: |
      Server={{ ip_zabbix }}
      ServerActive={{ ip_zabbix }}
      Hostname={{ inventory_hostname }}
    insertafter: EOF
  notify: restart zabbix-agent