---
# tasks file for proxy

# Установка основных пакетов
- name: Обновление apt
  apt:
    update_cache: yes

- name: Установка программ
  apt:
    name: "{{ packages_to_install }}"
    state: present

# настрйока nginx
- name: Удаление дефолтных конфигов nginx
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default

- name: Настройка конфига nginx
  template:
    src: http_proxy.j2
    dest: /etc/nginx/conf.d/http_proxy.conf
    owner: root
    group: root
    mode: '0664'
  notify: "Nginx Reloader"

- name: Настройка конфига nginx для zabbix
  template:
    src: http_zabbix.j2
    dest: /etc/nginx/conf.d/http_zabbix.conf
    owner: root
    group: root
    mode: '0664'
  notify: "Nginx Reloader"

# Настройка nfs
- name: Создание директории для монтирования NFS
  file:
    path: "{{ nfs_share }}"
    state: directory
    recurse: yes

- name: Настройка прав на директорию srv
  file:
    path: /srv/
    mode: '0775'
    recurse: yes

- name: конфиг nfs
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'

- name: перечитываем файл export
  ansible.builtin.command: exportfs -a

- name: enable nfs
  ansible.builtin.service:
    name: nfs-kernel-server
    enabled: yes
    state: started